---
version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
